### ISSUE TITLE
put tailwind 

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/weblib#1]
- tailwind
- libs for kelpler (needed for sign on)
- tailwind components
- playground for openrpc
- docsify
- mdbook

**Comment by timurgordon** [comment]
I don't think we can put tailwind and flowbite components in here. As per their [license](https://tailwindui.com/license): 

"Examples of usage not allowed by the license:

Creating a repository of your favorite Tailwind UI components or templates (or derivatives based on Tailwind UI components or templates) and publishing it publicly."

**Comment by timurgordon** [comment]
We can probably put the few that are open source, but not the licensed ones we purchased. Or we could keep this repository private, which is the way to go I think.
